# version: "3.9"
services:
  auth_service:
    build:
      context: .
      dockerfile: dockerfile
    container_name: auth_service
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:5015
      - ConnectionStrings__DefaultConnection=Host=postgres-authdb;Port=5432;Database=asptrial;Username=postgres;Password=Nigger!9;
    ports:
      - "5015:5015"
    restart: always
  postgres:
    image: postgres:14.20-trixie
    container_name: postgres-authdb
    environment:
      - POSTGRES_PASSWORD=Nigger!9
      - POSTGRES_USER=postgres
      - POSTGRES_DB=asptrial
    ports:
      - "5432:5432"
    volumes:
      - postgres-authdb:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-authdb:
